const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",

  //auth
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",

  // user
  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  CREATE_USER_FAILED: "CREATE_USER_FAILED",
  GET_LIST_USER_SUCCESS: "GET_LIST_USER_SUCCESS",
  GET_LIST_USER_FAILED: "GET_LIST_USER_FAILED",
  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAILED: "DELETE_USER_FAILED",
  EDIT_USER_SUCCESS: "EDIT_USER_SUCCESS",
  EDIT_USER_FAILED: "EDIT_USER_FAILED",

  // Gender
  GET_GENDER_START: "GET_GENDER_START",
  GET_GENDER_SUCCESS: "GET_GENDER_SUCCESS",
  GET_GENDER_FAILED: "GET_GENDER_FAILED",

  // Role
  GET_ROLE_SUCCESS: "GET_ROLE_SUCCESS",
  GET_ROLE_FAILED: "GET_ROLE_FAILED",
  GET_LIST_DOCTOR_SUCCESS: "GET_LIST_DOCTOR_SUCCESS",
  GET_LIST_DOCTOR_FAILED: "GET_LIST_DOCTOR_FAILED",

  // Position
  GET_POSITION_SUCCESS: "GET_POSITION_SUCCESS",
  GET_POSITION_FAILED: "GET_POSITION_FAILED",

  // All code
  GET_LIST_CODE_SUCCESS: "GET_LIST_CODE_SUCCESS",
  GET_LIST_CODE_FAILED: "GET_LIST_CODE_FAILED",

  // Markdown
  CREATE_MARKDOWN_DOCTOR_SUCCESS: "CREATE_MARKDOWN_DOCTOR_SUCCESS",
  CREATE_MARKDOWN_DOCTOR_FAILED: "CREATE_MARKDOWN_DOCTOR_FAILED",
});

export default actionTypes;
